<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BusinessCardMedia extends \AppBundle\Entity\BusinessCardMedia implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\BusinessCardMedia' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\BusinessCardMedia' . "\0" . 'businessCard', '' . "\0" . 'AppBundle\\Entity\\BusinessCardMedia' . "\0" . 'format', '' . "\0" . 'AppBundle\\Entity\\BusinessCardMedia' . "\0" . 'url'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\BusinessCardMedia' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\BusinessCardMedia' . "\0" . 'businessCard', '' . "\0" . 'AppBundle\\Entity\\BusinessCardMedia' . "\0" . 'format', '' . "\0" . 'AppBundle\\Entity\\BusinessCardMedia' . "\0" . 'url'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BusinessCardMedia $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormat', []);

        return parent::getFormat();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormat($format)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormat', [$format]);

        return parent::setFormat($format);
    }

    /**
     * {@inheritDoc}
     */
    public function setURL($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setURL', [$url]);

        return parent::setURL($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getURL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getURL', []);

        return parent::getURL();
    }

    /**
     * {@inheritDoc}
     */
    public function getBusinessCard()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBusinessCard', []);

        return parent::getBusinessCard();
    }

    /**
     * {@inheritDoc}
     */
    public function setBusinessCard(\AppBundle\Entity\BusinessCard $bc = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBusinessCard', [$bc]);

        return parent::setBusinessCard($bc);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addMediaEvent(\AppBundle\Entity\MediaEvent $mediaEvent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMediaEvent', [$mediaEvent]);

        return parent::addMediaEvent($mediaEvent);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMediaEvent(\AppBundle\Entity\MediaEvent $mediaEvent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMediaEvent', [$mediaEvent]);

        return parent::removeMediaEvent($mediaEvent);
    }

    /**
     * {@inheritDoc}
     */
    public function getMediaEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMediaEvent', []);

        return parent::getMediaEvent();
    }

}
