<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BusinessCard extends \AppBundle\Entity\BusinessCard implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'title', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'lastname', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'user', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'category', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'phone', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'company', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'fax', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'website', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'notes', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'about', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'logo', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'picture', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'finished', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'businessCardMedia'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'title', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'lastname', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'user', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'category', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'phone', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'company', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'fax', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'website', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'notes', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'about', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'logo', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'picture', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'finished', '' . "\0" . 'AppBundle\\Entity\\BusinessCard' . "\0" . 'businessCardMedia'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BusinessCard $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addBusinessCardMedia(\AppBundle\Entity\BusinessCardMedia $media)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBusinessCardMedia', [$media]);

        return parent::addBusinessCardMedia($media);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBusinessCardMedia(\AppBundle\Entity\BusinessCardMedia $like_)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBusinessCardMedia', [$like_]);

        return parent::removeBusinessCardMedia($like_);
    }

    /**
     * {@inheritDoc}
     */
    public function getBusinessCardMedia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBusinessCardMedia', []);

        return parent::getBusinessCardMedia();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompany($company)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompany', [$company]);

        return parent::setCompany($company);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompany()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompany', []);

        return parent::getCompany();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinished($finished)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinished', [$finished]);

        return parent::setFinished($finished);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinished()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinished', []);

        return parent::getFinished();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastname($lastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastname', [$lastname]);

        return parent::setLastname($lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastname', []);

        return parent::getLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setZip($zip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZip', [$zip]);

        return parent::setZip($zip);
    }

    /**
     * {@inheritDoc}
     */
    public function getZip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZip', []);

        return parent::getZip();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', [$fax]);

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', []);

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsite($website)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsite', [$website]);

        return parent::setWebsite($website);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsite', []);

        return parent::getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function getNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotes', []);

        return parent::getNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotes($notes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotes', [$notes]);

        return parent::setNotes($notes);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbout', []);

        return parent::getAbout();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbout($about)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbout', [$about]);

        return parent::setAbout($about);
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo($logo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', [$logo]);

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', []);

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPicture($picture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPicture', [$picture]);

        return parent::setPicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function getPicture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPicture', []);

        return parent::getPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\AppBundle\Entity\GroupCategory $category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\AppBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(\AppBundle\Entity\Address $address = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

}
